-- MySQL Script generated by MySQL Workbench
-- Mon Oct  4 16:24:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HHA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HHA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HHA` DEFAULT CHARACTER SET utf8 ;
USE `HHA` ;

-- -----------------------------------------------------
-- Table `HHA`.`Rehab_Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HHA`.`Rehab_Report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `beds_available` INT NULL,
  `bed_days` INT NULL,
  `patient_days` INT NULL,
  `hospitalised` INT NULL,
  `discharged` INT NULL,
  `self_discharges` INT NULL,
  `deaths_before_48` INT NULL,
  `deaths_after_48` INT NULL,
  `days_hospitalised` INT NULL,
  `referrals` INT NULL,
  `transfers` INT NULL,
  `stays` INT NULL,
  `admissions` INT NULL,
  `outpatients` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
