-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 15:59:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema Rehab_Report
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Rehab_Report
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS Rehab_Report DEFAULT CHARACTER SET utf8 ;
USE Rehab_Report ;

-- -----------------------------------------------------
-- Table Rehab_Report.Rehab_Report
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Rehab_Report.Rehab_Report (
  id INT NOT NULL AUTO_INCREMENT,
  date DATETIME NULL,
  department VARCHAR(45) NULL,
  beds_available INT NULL,
  bed_days INT NULL,
  patient_days INT NULL,
  hospitalised INT NULL,
  discharged INT NULL,
  self_discharges INT NULL,
  deaths_before_48 INT NULL,
  deaths_after_48 INT NULL,
  days_hospitalised INT NULL,
  referrals INT NULL,
  transfers INT NULL,
  stays INT NULL,
  admissions INT NULL,
  outpatients INT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE);


-- -----------------------------------------------------
-- Table Rehab_Report.Rehab_Deaths
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Rehab_Report.Rehab_Deaths (
  id INT NOT NULL AUTO_INCREMENT,
  report_id INT NOT NULL,
  before_48 TINYINT NULL,
  cause VARCHAR(45) NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE,
  INDEX report_id_idx (report_id ASC) VISIBLE,
  CONSTRAINT report_id
    FOREIGN KEY (report_id)
    REFERENCES Rehab_Report.Rehab_Report (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table Rehab_Report.Rehab_Discharges
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Rehab_Report.Rehab_Discharges (
  id INT NOT NULL AUTO_INCREMENT,
  report_id INT NOT NULL,
  successful INT NULL,
  reason VARCHAR(45) NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE,
  INDEX report_id_idx (report_id ASC) VISIBLE,
  CONSTRAINT report_id
    FOREIGN KEY (report_id)
    REFERENCES Rehab_Report.Rehab_Report (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    

-- -----------------------------------------------------
-- Table Rehab_Report.Rehab_Stays
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Rehab_Report.Rehab_Stays (
  id INT NOT NULL AUTO_INCREMENT,
  report_id INT NOT NULL,
  stay_length INT NULL,
  reason VARCHAR(45) NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE,
  INDEX report_id_idx (report_id ASC) VISIBLE,
  CONSTRAINT report_id
    FOREIGN KEY (report_id)
    REFERENCES Rehab_Report.Rehab_Report (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table Rehab_Report.Rehab_Admissions
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Rehab_Report.Rehab_Admissions (
  id INT NOT NULL AUTO_INCREMENT,
  report_id INT NOT NULL,
  age INT NULL,
  gender TINYINT NULL,
  from VARCHAR(45) NULL,
  cause VARCHAR(45) NULL,
  injury_to_rehab INT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE,
  INDEX report_id_idx (report_id ASC) VISIBLE,
  CONSTRAINT report_id
    FOREIGN KEY (report_id)
    REFERENCES Rehab_Report.Rehab_Report (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table Rehab_Report.Rehab_Outpatient
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Rehab_Report.Rehab_Outpatient (
  id INT NOT NULL,
  report_id INT NOT NULL,
  age INT NULL,
  gender TINYINT NULL,
  condition VARCHAR(45) NULL,
  PRIMARY KEY (id),
  INDEX report_id_idx (report_id ASC) VISIBLE,
  CONSTRAINT report_id
    FOREIGN KEY (report_id)
    REFERENCES Rehab_Report.Rehab_Report (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- GRANT SELECT ON Rehab_Report.Rehab_Deaths TO 'HHA'@'ceres-database';
-- GRANT INSERT ON Rehab_Report.Rehab_Deaths TO 'HHA'@'ceres-database';
-- GRANT DELETE ON Rehab_Report.Rehab_Deaths TO 'HHA'@'ceres-database';

ALTER USER 'HHA' IDENTIFIED WITH mysql_native_password BY 'password';

flush privileges;